language: python

python:
  - "3.5"
  - "3.3"
  - "2.7"

before_install:
    - sudo add-apt-repository -y ppa:mc3man/trusty-media
    - sudo apt-get update
    - sudo apt-get install ffmpeg gstreamer0.10-ffmpeg

install: pip install -U .
script: py.test
